# ddd4j-quarkus-sample-mq-kafka 配置

# Quarkus HTTP 端口
quarkus.http.port=8080

# ddd4j MQ 配置
ddd4j.mq.namespace=quarkus-kafka-sample
ddd4j.mq.default-topic=DEFAULT

# Kafka 连接配置
# 默认连接 localhost:9092，可通过环境变量覆盖
ddd4j.mq.kafka.bootstrap-servers=${DDD4J_MQ_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
ddd4j.mq.kafka.consumer-group=quarkus-kafka-sample
