# ddd4j-quarkus-sample-mq-disruptor 配置

# Quarkus HTTP 端口
quarkus.http.port=8080
quarkus.http.test-port=0
quarkus.index-dependency.mq-core.group-id=io.ddd4j.quarkus
quarkus.index-dependency.mq-core.artifact-id=ddd4j-quarkus-mq-core
quarkus.index-dependency.mq-broker.group-id=io.ddd4j.quarkus
quarkus.index-dependency.mq-broker.artifact-id=ddd4j-quarkus-mq-disruptor
ddd4j.mq.enabled=true
ddd4j.mq.broker=disruptor

# ddd4j MQ 配置
ddd4j.mq.namespace=quarkus-disruptor-sample
ddd4j.mq.default-topic=DEFAULT

# Disruptor 本地 MQ 配置（无外部依赖）
ddd4j.mq.disruptor.buffer-size=1024
ddd4j.mq.disruptor.wait-strategy=yielding
