<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j.quarkus</groupId>
        <artifactId>ddd4j-quarkus-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../ddd4j-quarkus-parent/pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-quarkus-ddd</artifactId>
    <description>fuinorg DDD/CQRS 契约聚合（无 Spring）</description>

    <dependencies>
        <dependency>
            <groupId>org.fuin.ddd4j</groupId>
            <artifactId>ddd-4-java-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.fuin.ddd4j</groupId>
            <artifactId>ddd-4-java-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>org.fuin.cqrs4j</groupId>
            <artifactId>cqrs-4-java-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.fuin.cqrs4j</groupId>
            <artifactId>cqrs-4-java-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.ddd4j.quarkus</groupId>
            <artifactId>ddd4j-quarkus-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.smallrye</groupId>
            <artifactId>jandex</artifactId>
        </dependency>
    </dependencies>

</project>
