<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j.quarkus</groupId>
        <artifactId>ddd4j-quarkus-mq</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-quarkus-mq-mqtt-mica</artifactId>
    <description>ddd4j-quarkus MQ - mqtt-mica：对齐 boot 模块结构，底层复用 ddd4j-mq-mqtt-mica。</description>

    <dependencies>
        <dependency>
            <groupId>io.ddd4j.quarkus</groupId>
            <artifactId>ddd4j-quarkus-mq-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-mq-mqtt-mica</artifactId>
            <version>${ddd4j.version}</version>
        </dependency>
    </dependencies>
</project>
